# workspaces und autostart, siehe https://github.com/basecamp/omarchy/discussions/472#discussioncomment-14763670
# um class herauszufinden: hyprctl clients

# ~/.config/hypr/workspaces.conf

# [optional] bind workspaces to monitors
# workspace = 1,monitor:eDP-2
# workspace = 2,monitor:HDMI-A-1
# workspace = 3,monitor:HDMI-A-1
# workspace = 4,monitor:HDMI-A-1
# workspace = 5,monitor:HDMI-A-1

# define how each app should be displayed, in which wbrave-web.whatsapp.com__-Defaultorkspace, and with which effects (eg. fullscreen)
windowrule = workspace 1, match:class Alacritty
#windowrule = workspace 2, match:class zen
#windowrule = workspace 3, match:class code, fullscreen on
windowrule = workspace 3, match:class org.mozilla.Thunderbird
windowrule = workspace 5, match:class discord
windowrule = workspace 5, match:class slack
windowrule = workspace 5, match:class org.telegram.desktop
windowrule = workspace 5, match:class signal
windowrule = workspace 5, match:class brave-web.whatsapp.com__-Default
#windowrule = workspace 5, match:class spotify

# launch apps at startup with the silent flag to prevent focus from switching workspaces
exec-once = [workspace 1 silent] alacritty
exec-once = [workspace 1 silent] brave
#exec-once = [workspace 2 silent] alacritty
exec-once = [workspace 2 silent] brave
exec-once = [workspace 3 silent] thunderbird
exec-once = [workspace 3 silent] slack
exec-once = [workspace 5 silent] omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
exec-once = [workspace 5 silent] signal-desktop
exec-once = [workspace 5 silent] Telegram
