#! /bin/sh

bspc config top_padding 30
bspc config bottom_padding 0


pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d I II III IV V
bspc monitor -d code II III

bspc config border_width         4
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a jetbrains-studio desktop='^3' follow=on
bspc rule -a Alacritty desktop='^1' follow=on


# starte Polybar mit polybar-themes von adi1090x
bash ~/.config/polybar/launch.sh --forest

